apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ingestion.yaml
  - ../../base/streaming.yaml
  - ../../base/firestore.yaml
  - ../../base/redis.yaml
configMapGenerator:
  - name: configuration
    envs:
    - application.env
patches:
  - path: ingestion-zk.json
    target:
      kind: StatefulSet
      name: zk
      version: v1
  - path: streaming-deployment.json
    target:
      kind: Deployment
      name: streaming-deployment
      version: v1
