resources:
  - ../../base/ingestion.yaml
  - ../../base/streaming.yaml
  - ../../base/firestore.yaml
  - ../../base/redis.yaml
configMapGenerator:
  - name: configuration
    envs:
    - application.env
