apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - zk
              topologyKey: "kubernetes.io/hostname"
      containers:
        # To debug the local zookeeper instance, run 
        # kubectl exec -it zk-0 --container kubernetes-zookeeper -- sh
        # https://kubernetes.io/docs/tasks/debug/debug-application/get-shell-running-container/#opening-a-shell-when-a-pod-has-more-than-one-container
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: "zookeeper:latest"
        env:
          - name: ZOO_4LW_COMMANDS_WHITELIST
            value: "*"
          - name: ZOO_MY_ID
            valueFrom:
              fieldRef:
                # We need a way to assign each Zookeeper server in the ensemble a unique ID.
                # The easiest way is to use the ordinal index, which is available with the pod-index
                # label in a StatefulSet.
                # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-index-label
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          - name: ZOO_SERVERS
            # We need the FQDNs of each pod in our headless service, but it's not possible to get this value
            # dynamically based on the number of replicas we are using. Based on the DNS documenation for services,
            # FQDNs are formatted as <pod-name>.<service name>.<namespace>.svc.<cluster domain>, so they are listed
            # exhaustively here.
            # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
            value: |
              server.0=zk-0.zk-hs.default.svc.cluster.local:2888:3888;2181
              server.1=zk-1.zk-hs.default.svc.cluster.local:2888:3888;2181
              server.2=zk-2.zk-hs.default.svc.cluster.local:2888:3888;2181
          - name: ZOO_CFG_EXTRA
            # Based on the Zookeeper configuration documentation, the following configurations in zoo.cfg are required.
            # https://zookeeper.apache.org/doc/r3.5.7/zookeeperAdmin.html#sc_minimumConfiguration
            value: "clientPort=2181 dataDir=/data tickTime=2000 dataLogDir=/datalog"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo \"ruok\" | \
              nc localhost 2181 | \
              grep imok"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo \"ruok\" | \
              nc localhost 2181 | \
              grep \"imok\""
          initialDelaySeconds: 10
          timeoutSeconds: 5
      - name: ingestion-service
        imagePullPolicy: Always
        image: localhost:5000/ingestion-service
        resources:
          requests:
            memory: "0.3Gi"
            cpu: "0.4"
        env:
          - name: POD_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          - name: ZOO_SERVERS
            value: |
              zk-0.zk-hs.default.svc.cluster.local:2181,
              zk-1.zk-hs.default.svc.cluster.local:2181,
              zk-2.zk-hs.default.svc.cluster.local:2181
          - name: ENVIRONMENT
            value: "development"
      securityContext:
        runAsUser: 0
