apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
            name: redis-port
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firestore-deployment
  labels:
    app: firestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firestore
  template:
    metadata:
      labels:
        app: firestore
    spec:
      containers:
        - name: firestore
          image: localhost:5000/firestore:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: firestore-port
          env:
            - name: FIRESTORE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: FIRESTORE_PROJECT_ID
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: GOOGLE_CLOUD_PROJECT
            - name: GCLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: GCLOUD_PROJECT
---
apiVersion: v1
kind: Service
metadata:
  name: firestore-service
  labels:
    app: firestore
spec:
  selector:
    app: firestore
  ports:
    - port: 8080
      targetPort: firestore-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deployment
  labels:
    app: streaming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: localhost:5000/streaming:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: streaming-port
        env:
          - name: FIRESTORE_EMULATOR_HOST
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: FIRESTORE_EMULATOR_HOST
          - name: FIRESTORE_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: FIRESTORE_PROJECT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  labels:
    app: streaming
spec:
  type: LoadBalancer
  selector:
    app: streaming
  ports:
    - protocol: TCP
      port: 80
      name: service-port
      targetPort: streaming-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx-ingress
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streaming-service
            port:
              name: service-port
