FROM python:3.10.12-alpine
ENV PYTHONUNBUFFERED=1

COPY src/streaming src/streaming
COPY test/integration_tests/streaming test/integration_tests/streaming
RUN pip3 install -r src/streaming/requirements.txt

CMD [ "python3", "-m", "unittest", "discover", "test/integration_tests/streaming" ]
