apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: not-used
spec:
  template:
    spec:
      containers:
      - name: ingestion-service
        resources:
          requests:
            memory: "0.3Gi"
            cpu: "0.4"
        env:
          - name: POD_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          - name: ZOO_SERVERS
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: INGESTION_ZOO_SERVERS
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: ENVIRONMENT
          - name: FIRESTORE_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: FIRESTORE_PROJECT_ID
