apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ingestion.yaml
  - ../../base/streaming.yaml
  - ../../base/redis.yaml
configMapGenerator:
  - name: configuration
    envs:
    - application.env
patches:
  - path: streaming-deployment.yaml
    target:
      name: streaming-deployment
      labelSelector: "dataStore=firestore"
  - path: ingestion-zk.yaml
    target:
      name: zk
      labelSelector: "dataStore=firestore"
