apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-used
spec:
  template:
    spec:
      containers:
      - name: streaming
        env:
          - name: FIRESTORE_EMULATOR_HOST
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: FIRESTORE_EMULATOR_HOST
          - name: FIRESTORE_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: FIRESTORE_PROJECT_ID
