apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  ZOO_4LW_COMMANDS_WHITELIST: "*"
  # We need the FQDNs of each pod in our headless service, but it's not possible to get this value
  # dynamically based on the number of replicas we are using. Based on the DNS documenation for services,
  # FQDNs are formatted as <pod-name>.<service name>.<namespace>.svc.<cluster domain>, so they are listed
  # exhaustively here.
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
  ZOO_SERVERS: |
    server.0=zk-0.zk-hs.default.svc.cluster.local:2888:3888;2181
    server.1=zk-1.zk-hs.default.svc.cluster.local:2888:3888;2181
    server.2=zk-2.zk-hs.default.svc.cluster.local:2888:3888;2181
  INGESTION_ZOO_SERVERS: |
    zk-0.zk-hs.default.svc.cluster.local:2181,
    zk-1.zk-hs.default.svc.cluster.local:2181,
    zk-2.zk-hs.default.svc.cluster.local:2181
  # Based on the Zookeeper configuration documentation, the following configurations in zoo.cfg are required.
  # https://zookeeper.apache.org/doc/r3.5.7/zookeeperAdmin.html#sc_minimumConfiguration
  ZOO_CFG_EXTRA: "clientPort=2181 dataDir=/data tickTime=2000 dataLogDir=/datalog"
  ENVIRONMENT: "development"
  GOOGLE_CLOUD_PROJECT: open-notify
  GCLOUD_PROJECT: open-notify
  FIRESTORE_EMULATOR_HOST: firestore-service.default.svc.cluster.local:8080
  FIRESTORE_PROJECT_ID: open-notify
