apiVersion: apps/v1
kind: Deployment
metadata:
  name: firestore-deployment
  labels:
    app: firestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firestore
  template:
    metadata:
      labels:
        app: firestore
    spec:
      containers:
        - name: firestore
          image: localhost:5000/firestore:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: firestore-port
          env:
            - name: FIRESTORE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: FIRESTORE_PROJECT_ID
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: GOOGLE_CLOUD_PROJECT
            - name: GCLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: GCLOUD_PROJECT
---
apiVersion: v1
kind: Service
metadata:
  name: firestore-service
  labels:
    app: firestore
spec:
  selector:
    app: firestore
  ports:
    - port: 8080
      targetPort: firestore-port
