apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deployment
  labels:
    app: streaming
    dataStore: firestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: streaming:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: streaming-port
        resources:
          requests:
            memory: "71Mi"
            cpu: "2m"
          limits:
            memory: "286Mi"
            cpu: "9m"
            
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  labels:
    app: streaming
spec:
  type: LoadBalancer
  selector:
    app: streaming
  ports:
    - protocol: TCP
      port: 80
      name: service-port
      targetPort: streaming-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx-ingress
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streaming-service
            port:
              name: service-port
